services:
    php:
        image: tugboatqa/php:8.3-apache
        default: true
        commands:
            init:
                - 
            update:
                - composer install --optimize-autoloader
                - php artisan winter:install
